### ISSUE TITLE
Client ID & Key configuration

### ISSUE THREAD

**Issue by tommytran732** [umass-compsci220/Ocelot#131]
Hi, I am trying to self host Ocelot, but it seems like I need to specify my own OAuth client key & id. I cannot seem to find the configuration to put them in. Where should I find it?

**Comment by arjunguha** [comment]
@lchsam may be able to answer this question. Are you trying to host it as a Google Cloud Function? In principle, it doesn't require Google services. In practice, we haven't bothered making it portable.

**Comment by tommytran732** [comment]
> @lchsam may be able to answer this question. Are you trying to host it as a Google Cloud Function? In principle, it doesn't require Google services. In practice, we haven't bothered making it portable.

Oh, I am just following the docs, doing yarn install and yarn run serve-local. The problem is that I cannot log into my self hosted instance (because the redirect uri and whatnot is wrong), so I assume that I need my own OAuth key.

**Comment by tommytran732** [comment]
I found that the client id seems to be in frontend/server/server.ts, but I cannot seem to find where to put the client secret. Changing the ID & hostname gives me "The authentication server seems to be down. Try again in a bit."

**Comment by lchsam** [comment]
If my memory serves me correctly, I believe you don't need to put the client secret in the application. The "The authentication server seems to be down. Try again in a bit." is most likely because the backend is not set up properly. 

We did not make it portable so our instructions were mostly written for those who already have access to our Google backend resources. Logging in for Ocelot would unfortunately not work because it requires a backend server. Our code is set up so that one can host the local frontend site and the local backend server, but the local backend server would still rely on Google Cloud Platform for storing user information (e.g. user-created files).
If you want Ocelot to just have a running IDE and REPL, what you're doing should work.

If you're willing to set up Google Cloud Platform (i.e. deploy your own Google services), I can definitely give a rundown on what needs to be set up.

**Comment by tommytran732** [comment]
> If my memory serves me correctly, I believe you don't need to put the client secret in the application. The "The authentication server seems to be down. Try again in a bit." is most likely because the backend is not set up properly.
> 
> We did not make it portable so our instructions were mostly written for those who already have access to our Google backend resources. Logging in for Ocelot would unfortunately not work because it requires a backend server. Our code is set up so that one can host the local frontend site and the local backend server, but the local backend server would still rely on Google Cloud Platform for storing user information (e.g. user-created files).
> If you want Ocelot to just have a running IDE and REPL, what you're doing should work.
> 
> If you're willing to set up Google Cloud Platform (i.e. deploy your own Google services), I can definitely give a rundown on what needs to be set up.

I am willing to setup my own GCP. If you could give me a run down to set it up, it would be absolutely fantastic. I want to be able to save files and use lib220 and whatnot.

Just out of curiosity, are you planning to add local authentication & storage at some point?

**Comment by lchsam** [comment]
I have not planned to add them but it sounds like a good idea. Creating/editing files locally without logging in is probably a good first step. I believe we don't have plans to add that feature but contributions are definitely welcomed.

Here's a rundown of what needs to be modified in order to host Ocelot locally (frontend + backend + Google Cloud Platform):
1. Set up GCP
   - Create a Project in Google Cloud Platform, [instructions here](https://cloud.google.com/resource-manager/docs/creating-managing-projects)
   - Create 2 Google Storage Buckets ([instructions here](https://cloud.google.com/storage/docs/creating-buckets)) with names: `ocelot-student-files` and `ocelot-student-history`.
   - Create a Google Datastore ([instructions here](https://cloud.google.com/datastore/docs/quickstart#create_a_database)) (Firestore in Datastore mode). In the Datastore, create an entity with the Kind set as `CS220AllowedAccounts` and the name of the entity set as the email you'll use to log in to Ocelot.
   - Use the [`README`](https://github.com/umass-compsci220/Ocelot/tree/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb#dependencies) to install GCP's SDK and link it to your GCP project
2. Modify [`backend/ts/index.ts`](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/backend/ts/index.ts)
   - Remove [line 19](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/backend/ts/index.ts#L19)
   - Remove [line 46](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/backend/ts/index.ts#L46)
   - Replace [line 47](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/backend/ts/index.ts#L47) with `return {clientID: 'insert-your-google-auth-client-id', sessionDuration: 5};`. I believe you already have a Google Auth Client id created but just in case, [here's how to create one.](https://developers.google.com/identity/sign-in/web/sign-in)

3. Modify [`frontend/src/secrets.ts`](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/frontend/src/secrets.ts)
   - `CLD_FN_BASE_URL` - set the entire URL to be `https://localhost:8000/`
   - `LOGIN_CLIENT_ID` - replace the entire URL to the Google Auth client ID you created.

4. Building and running the frontend and backend
   - Follow the [`README`](https://github.com/umass-compsci220/Ocelot/tree/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb#build--run-instructions) for Build and Run instructions.

Let me know if you encounter any problems.

**Comment by tommytran732** [comment]
> * ocelot-student-files

Hi,

The bucket names must be unique. It seems like the ones you mentioned had already been taken. Can I use different bucket names for this?

**Comment by lchsam** [comment]
Oh, I see. Yes, you can. You can create buckets with different names and just change the bucket names in [Line 18](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/backend/ts/index.ts#L18) and [Line 20](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/backend/ts/index.ts#L20) in `backend/ts/index.ts` to the buckets you created.

**Comment by tommytran732** [comment]
It still does not seem to work :/

I have made those changes [here](https://github.com/tommytran732/Ocelot)... it would be great if you could have a look. I did log into Google Cloud SDK on my VPS, select my project, create the appropriate OAuth ID & Google Datastore. I also created the storage buckets (multi-region, standard class, encryption key managed by Google).

**Comment by lchsam** [comment]
It looks like I made a mistake in the directions and I also found one bug with locally running the backend (interestingly, the bug disappears when deployed).
- When creating an entity in the Datastore, make sure that the Key identifier of the entity is set to Custom name instead of Numeric ID. You would set the custom name to your email to log in to Ocelot.
- When creating a OAuth Client ID, there's a 'Authorized JavaScript origins' section. You can modify your existing client ID and add `http://localhost:8080` as a URI for that section.
- For modifying [`frontend/src/secrets.ts`](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/frontend/src/secrets.ts), set `CLD_FN_BASE_URL` to `http://localhost:8000/` (I accidentally, used `https` in the directions)
- In `backend/ts/index.ts`, we have to move this function call, `paws.use(morgan(...))` in [line 525](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/backend/ts/index.ts#L525), down to [line 542](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/backend/ts/index.ts#L542).
The reason is that `morgan(...)` uses `req.body` for logging info, but there is no `body` in `req` until after we use `bodyParser.json()` ([line 541](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/backend/ts/index.ts#L541)). After testing around Google Cloud Functions (the service the backend runs on), this bug does not show up in production because Cloud Functions seem to already have a `req.body` created without `bodyParser.json()`

Sorry for the confusing directions. We found a bug which is great.
I'll update the original directions with the updated info.
Let me know if you encounter any more problems.

**Comment by tommytran732** [comment]
Hi, it is still not working and I am still getting the same error. I noticed a few things: 

In line [535](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/backend/ts/index.ts#L535), the origin is set to www.ocelot-ide.org, should I change this to the domain/subdomain I am using instead?

Since I am using an NGINX reverse proxy with a subdomain, do I need to add `http://localhost:8000/` to the 'Authorized JavaScript origins' section? Right now I have both my subdomain and http://localhost:8080  as authorized, by I am asking just in case.

 I don't know if this is related or not, but I am running NodeJS 10 (it built just fine) and I am seeing this in my syslog:

![image](https://user-images.githubusercontent.com/57488583/94978953-0e164480-04ee-11eb-9987-c5044f63ebed.png)

**Comment by lchsam** [comment]
The `WARN` and `ERROR` shouldn't affect it, Stackdriver is just for logging. I recommend using Node.js 8, but it sounds like you ran `yarn install` and `yarn run build` for both frontend and backend with no problems. I think you should be fine. If you did see errors when you `yarn install` for either frontend or backend, there might be a problem and you should revert to Node.js 8.

Changing line 535 to your own domain will definitely help.
What you have for Authorized JS origins should work.

Do you encounter the same error even after changing line 535 to your domain?

**Comment by lchsam** [comment]
I forgot to mention, clearing browser cache after making changes to the Google client id credentials may also help. (Clear browsing data -> Cached images and files). It helped me properly log in.

**Comment by tommytran732** [comment]
It is still not working :/ 

Apparently, the front end is having connection issues to the backend for whatever reason.
![image](https://user-images.githubusercontent.com/57488583/94980546-ab767600-04f8-11eb-9b95-234f04e164bf.png)

The thing is, the backend is clearly running:
![image](https://user-images.githubusercontent.com/57488583/94980563-dc56ab00-04f8-11eb-981d-1a2c28792853.png)
![image](https://user-images.githubusercontent.com/57488583/94980571-e8426d00-04f8-11eb-8323-8d286b3d548f.png)

**Comment by tommytran732** [comment]
Okay, so it seems like the issue I mentioned above is caused by the fact that it is trying to make the browser fetch `http://127.0.0.1:8000` while I am using a different computer from the one hosting Ocelot.

I solved this by making another NGINX reverse proxy to the backend and setup a subdomain for the backend. I have also updated the link in secrets.ts from http://127.0.0.1:8000 to the backend's subdomain. 

Now it seems like we are getting 500 error code... I suspect it could be something wrong with the backend's code, I hope you could have a look:

![image](https://user-images.githubusercontent.com/57488583/94997974-a9ee9180-057c-11eb-86d8-b4f8e15363c4.png)

**Comment by tommytran732** [comment]
Okay, so it seems like the issue I mentioned above is caused by the fact that it is trying to make the browser fetch `http://127.0.0.1:8000` while I am using a different computer from the one hosting Ocelot.

I solved this by making another NGINX reverse proxy to the backend and setup a subdomain for the backend. I have also updated the link in secrets.ts from http://127.0.0.1:8000 to the backend's subdomain. 

Now it seems like we are getting 500 error code... I suspect it could be something wrong with the backend's code, I hope you could have a look:

![image](https://user-images.githubusercontent.com/57488583/94998287-b542bc80-057e-11eb-89e7-4313e7bb3a49.png)
![image](https://user-images.githubusercontent.com/57488583/94998020-06ea4780-057d-11eb-9f3c-4427c01b1483.png)

My google SDK is connected to the google cloud project and the backend/ts/index.ts file has the client ID as your instruction says. I don't know what could be causing this issue.

**Comment by lchsam** [comment]
Thank you for the screenshots. I don't think I have encountered this issue but I believe it might be the Google SDK not authenticated correctly. The `/login 500` message means that we have to fix the errors that popped up before it. So, it looks like we have to fix `Error: Unexpected error while acquiring application default credentials`. 

I came across this [stackoverflow post](https://stackoverflow.com/questions/42043611/could-not-load-the-default-credentials-node-js-google-compute-engine-tutorial/42097631) about the issue, and it looks like you have to run `gcloud auth application-default login`. What I would do is make sure the Google SDK is installed on the machine that runs the backend and run `gcloud auth application-default login` (It brings up your browser for you to log in with Google). 

If that does not work, you can try:
- Reverting the Google Cloud SDK to 310.0.0 (This is version my machine uses), [instructions here](https://stackoverflow.com/questions/45370810/reverting-to-old-google-cloud-sdk-shell-version) and rerunning the set up in the repo README.
- or, you can instead deploy the backend to your own Google Cloud Function, that should run the backend code in the same environment as what our production runs in.
   - To deploy it, navigate to `backend/` and run `yarn run build`. 
   - run `gcloud functions deploy backend-function --entry-point paws --runtime nodejs8 --trigger-http` (this deploys a http cloud function with name `backend-function` which uses the [exported `paws` object](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/backend/ts/index.ts#L499). Be sure to then set it to allow unauthenticated invocations. After the function is created, there is a URL endpoint to the function. Replace `CLD_FN_BASE_URL` in `frontend/src/secrets.ts` to that URL. 

Hope that solves your problem.

**Comment by tommytran732** [comment]
Thank you so much for your help. I have found the issue. The problem was that I was running ocelot backend using systemd and it did not load in the GOOGLE_APPLICATION_CREDENTIALS variable in, which is what caused the problem.

**Comment by tommytran732** [comment]
Thank you so much for your help. I have found the issue. The problem was that I was running ocelot backend using systemd and it did not load in the GOOGLE_APPLICATION_CREDENTIALS variable in, which is what caused the problem.

**Comment by tommytran732** [comment]
For future references, this is the systemd services that should be working:

`[Unit]
Description=Ocelot Frontend
After=network.target

[Service]
WorkingDirectory=/root/Ocelot/frontend
Restart=always
ExecStart=/usr/bin/yarn run serve-local

[Install]
WantedBy=multi-user.target`

`[Unit]
Description=Ocelot Frontend
After=network.target

[Service]
WorkingDirectory=/root/Ocelot/frontend
Restart=always
ExecStart=yarn run serve-local

[Install]
WantedBy=multi-user.target
root@Ocelot:/etc/systemd/system# cat ocelot-backend.service 
[Unit]
Description=Ocelot Backend
After=network.target

[Service]
WorkingDirectory=/root/Ocelot/backend
Restart=always
ExecStart=/usr/bin/yarn run serve
Environment="GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json"
[Install]
WantedBy=multi-user.target
`

**Comment by tommytran732** [comment]
Oh, and out of curiosity, is it possible to use the buckets with my own encryption keys?

**Comment by tommytran732** [comment]
Update: It is still connecting to your google cloud function somehow when I am trying to use the libraries like lib220 :(
![image (1)](https://user-images.githubusercontent.com/57488583/95021383-afacab80-063e-11eb-91e8-79e6b74c480d.png)

Also, out of curiosity, is it possible to make ocelot work with the buckets using my own encryption key or do the keys have to be managed by Google?

**Comment by tommytran732** [comment]
Okay, so the issue appears to be that lib220 are making calls to your Google Cloud functions. Do you know how I should go about fixing this?

![image](https://user-images.githubusercontent.com/57488583/95023541-a70ea200-064b-11eb-95b1-62ee3a89a706.png)

**Comment by lchsam** [comment]
Great that authentication problem and the lib220 problem are fixed! Thanks for providing the service files. 

I'll just list out the directions on how to fix it for future reference:
1. Fork [ocelot-settings](https://github.com/umass-compsci220/ocelot-settings) (The repository that contains libraries like `lib220`.)
2. Specifically modify [`src/lib220.ts`](https://github.com/umass-compsci220/ocelot-settings/blob/1d598ff782679c03cdee021089460efd5aad4025/src/lib220.ts) in the repository, replacing the [`baseUrl`](https://github.com/umass-compsci220/ocelot-settings/blob/1d598ff782679c03cdee021089460efd5aad4025/src/lib220.ts#L269) with your own url to the backend. 
3. Run `yarn install`, and `yarn run build`.
4. Push those changes to your fork.
5. Update [`libraries.json`](https://github.com/umass-compsci220/ocelot-settings/blob/1d598ff782679c03cdee021089460efd5aad4025/libraries.json) and [`libraries-beta.json`](https://github.com/umass-compsci220/ocelot-settings/blob/1d598ff782679c03cdee021089460efd5aad4025/libraries-beta.json) (if you plan to have beta versions of your own) to have URLs that point to your Fork's libraries. (`dist/lib220.js`, `dist/oracle.js`...etc)
6. Modify `MODULE_WL_URL` in [`frontend/src/secrets.ts`](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/frontend/src/secrets.ts) to refer to your fork of `libraries.json`/`libraries-beta.json`
7. Rebuild your frontend (`yarn run build` in `frontend/`) and deploy it.

As for using your own encryption key, I believe this [Google Cloud documentation](https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-nodejs) helps, especially the 'Passing credentials manually' section. The gist is that there are three ways to manage credentials.
One is having Google manage it and running `gcloud auth application-default` which is what you did.
 
The second way is to create a service account, generate a service account JSON key and export `GOOGLE_APPLICATION_CREDENTIALS` environment variable with it equal to the path to the JSON key. 

Third is to provide the path of the JSON key directly in your code (e.g. `const storage = new Storage({projectId, keyFilename});`). 

Hope that helps.

**Comment by tommytran732** [comment]
> Great that authentication problem and the lib220 problem are fixed! Thanks for providing the service files.
> 
> I'll just list out the directions on how to fix it for future reference:
> 
> 1. Fork [ocelot-settings](https://github.com/umass-compsci220/ocelot-settings) (The repository that contains libraries like `lib220`.)
> 2. Specifically modify [`src/lib220.ts`](https://github.com/umass-compsci220/ocelot-settings/blob/1d598ff782679c03cdee021089460efd5aad4025/src/lib220.ts) in the repository, replacing the [`baseUrl`](https://github.com/umass-compsci220/ocelot-settings/blob/1d598ff782679c03cdee021089460efd5aad4025/src/lib220.ts#L269) with your own url to the backend.
> 3. Run `yarn install`, and `yarn run build`.
> 4. Push those changes to your fork.
> 5. Update [`libraries.json`](https://github.com/umass-compsci220/ocelot-settings/blob/1d598ff782679c03cdee021089460efd5aad4025/libraries.json) and [`libraries-beta.json`](https://github.com/umass-compsci220/ocelot-settings/blob/1d598ff782679c03cdee021089460efd5aad4025/libraries-beta.json) (if you plan to have beta versions of your own) to have URLs that point to your Fork's libraries. (`dist/lib220.js`, `dist/oracle.js`...etc)
> 6. Modify `MODULE_WL_URL` in [`frontend/src/secrets.ts`](https://github.com/umass-compsci220/Ocelot/blob/ddd4fbd138d7ccc3c598b183ab1e5a86f75f7eeb/frontend/src/secrets.ts) to refer to your fork of `libraries.json`/`libraries-beta.json`
> 7. Rebuild your frontend (`yarn run build` in `frontend/`) and deploy it.
> 
> As for using your own encryption key, I believe this [Google Cloud documentation](https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-nodejs) helps, especially the 'Passing credentials manually' section. The gist is that there are three ways to manage credentials.
> One is having Google manage it and running `gcloud auth application-default` which is what you did.
> 
> The second way is to create a service account, generate a service account JSON key and export `GOOGLE_APPLICATION_CREDENTIALS` environment variable with it equal to the path to the JSON key.
> 
> Third is to provide the path of the JSON key directly in your code (e.g. `const storage = new Storage({projectId, keyFilename});`).
> 
> Hope that helps.
> Let me know if you encounter any more problems.

Thank you. I will try with my own encryption keys tonight and let you know. However, I also want to note that both src/lib220.ts and dist/lib220.ts have to be changed. In fact, the libraries.json seems to be referencing the file in dist instead of src.

**Comment by lchsam** [comment]
> Thank you. I will try with my own encryption keys tonight and let you know. However, I also want to note that both src/lib220.ts and dist/lib220.ts have to be changed. In fact, the libraries.json seems to be referencing the file in dist instead of src.

Great, glad to have helped!
Yes that's correct. Thanks for pointing that out. I'll fix my directions. What step 3's `yarn run build` specifically does is update the `.js` files in `dist/` given the updated `.ts` files in `src/`.

**Comment by tommytran732** [comment]
Oh, there is another thing I want to ask:

I noticed that on the production version of Ocelot, it saves the history of all changes. That does not seem to be the case with my self hosted one (it only saves the last few changes). Where is this behavior set? Is it the retention policy for the history bucket?

I also see that when I file is marked for deletion, it is only deleted from the student files bucket. A copy of it is still saved in the history one. This appears to be the case for both my self hosted and the production version. In fact, after deleting a file, you can create a new file with the same name on Ocelot and access the previous versions of it. Is this an intended behavior or is it a bug?

**Comment by lchsam** [comment]
Oh right, I forgot to add that to the directions. There is [Objecting versioning](https://cloud.google.com/storage/docs/object-versioning) for buckets. You can enable it for the history bucket in the terminal (e.g. `gsutil versioning set on gs://ocelot-student-history`), more [info on how to use it here](https://cloud.google.com/storage/docs/using-object-versioning). Enabling retention policy would actually prevent buckets to use object versioning.
> I also see that when I file is marked for deletion, it is only deleted from the student files bucket. A copy of it is still saved in the history one. This appears to be the case for both my self hosted and the production version. In fact, after deleting a file, you can create a new file with the same name on Ocelot and access the previous versions of it. Is this an intended behavior or is it a bug?

That is a good question. Thanks for pointing it out. We may have just overlooked this so, this could be a bug. 
@arjunguha what do you think?

**Comment by arjunguha** [comment]
Right, we retain files in the history bucket, even after it is deleted from the primary files bucket. That is by design.

**Comment by tommytran732** [comment]
> Right, we retain files in the history bucket, even after it is deleted from the primary files bucket. That is by design.

Oh, may I ask why so? I think most students would expect that when they delete something, it's completely deleted and that there will not be a permanent record of everything they have ever put on Ocelot. It will also save money for the university as storage will not be wasted on unneeded files :)

**Comment by tommytran732** [comment]
> Right, we retain files in the history bucket, even after it is deleted from the primary files bucket. That is by design.

Oh, may I ask why so?

**Comment by arjunguha** [comment]
I'm curious -- are you using Ocelot to teach a class?

**Comment by tommytran732** [comment]
No, I just like self hosting stuff and running my own system. I like keeping my system clean and what not, and just found it is kind of odd that it doesn't delete files from the database especially when it says they will all be permanently deleted when you click on the delete button.

**Comment by arjunguha** [comment]
From my perspective, data on Ocelot are FERPA-protected student records. I believe we are required to retain them for two years, though I'm not a lawyer. :) Regardless, there are limitations on what we can do with them. Keeping deleted files in history has been helpful for a lot of students. Let me know if you need help setting this up to teach a class.
